color0       #484D4D
color8       #959A90
color1       #45949C
color9       #45949C
color2       #72967A
color10      #72967A
color3       #A39980
color11      #A39980
color4       #A6A6B2
color12      #A6A6B2
color5       #73D5C2
color13      #73D5C2
color6       #BCCBAC
color14      #BCCBAC
color7       #D5DDCD
color15      #D5DDCD